app.admin.username=${ADMIN_USERNAME:admin}
spring.datasource.url=jdbc:sqlite:${DB_PATH:./mydb.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
spring.devtools.restart.enabled=true
spring.thymeleaf.cache=false
server.servlet.session.timeout=90d
server.servlet.session.cookie.max-age=90d