spring.datasource.url=jdbc:sqlite:./mydb.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
spring.devtools.restart.enabled=true
spring.thymeleaf.cache=false